name: docsEnv
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3.11
  - sphinx
  - nbsphinx
  - pandoc
  - pip:
    - sphinx-press-theme
    - sphinx-book-theme
    - myst-parser
